#!/usr/bin/env python3
"""
clock_test_tool.py - a structural test for finite-state noise-model
compatibility, run on real surface-code syndrome data.

THE TEST (corrected statistic, v2; scope corrected, v2.2).  For a stationary binary stream
s_t (one stabilizer's detection events over QEC rounds), estimate the
run statistics p(1^n) = Pr[s_t = ... = s_{t+n-1} = 1] and form the
OFFSET Hankel matrix H[i, j] = p(1^(i+j+1)), 0 <= i, j <= m (the
n = 0 entry p(1^0) = 1 is NOT part of the moment structure and is
excluded - including it can falsely sign legitimate periodic models,
e.g. a deterministic two-state alternator).  THEOREM (v2.2 SCOPE - Moore form): if the stream is generated by a
finite hidden-Markov model in MOORE FORM (state-conditional
emissions) whose chain is REVERSIBLE (detailed balance), then
m_k = p(1^(k+1)) is a Hamburger moment sequence (detailed-balance
symmetrization: m_k = <u, M^k u> with M symmetric), so H is PSD for
every m.  v2.2 CORRECTION (hostile review): the v2.1 claim
"no reversible finite-state model of any dimension" was FALSE under
the Mealy (edge-emission) reading - a Mealy model on a reversible
chain converts to a Moore model on the EDGE chain, and the edge
chain of a reversible chain is NOT reversible (the back-transition
(j,k)->(i,j) needs k=i).  Decisive counterexample: the textbook
pair-mechanism model (iid mu + symmetric edge emissions) IS a Mealy
model on a reversible (iid) chain, and it SIGNS.  A statistically
SIGNED H therefore certifies: no reversible MOORE-form hidden-Markov
realization of any dimension; if
in addition the signature is aperiodic (irrational-frequency - no
rational autocorrelation peak), the Perron-Frobenius obstruction
excludes EVERY finite-state model.  Structural, not parametric.

ROBUSTNESS PROPERTY (important for real data): a convex mixture of
moment sequences is a moment sequence, so shot-to-shot drift or
parameter wander CANNOT sign the Hankel - pooling over shots is safe,
and only genuinely oscillatory (complex-spectrum) environment
structure can produce a violation.

STATISTICS (v2.2).  lambda_min(H_hat) with a bootstrap over SHOTS
(B = 2000 resamples, per-shot run-count resampling - identical
statistic to re-forming runs, vectorized); verdict SIGNED only if
the basic-bootstrap 97.5% upper bound is < 0; PASS otherwise.
Andrews-2000 caveat: at the rank-deficient boundary the bootstrap is
not consistent for extremal eigenvalues; the basic interval corrects
first-order bias only, and weak streams (|lam| ~ 3e-4) are flagged.
A conservative Bonferroni line (x1.6 margin inflation, normal
approx, 64 tests at family 5%) is printed in the aggregate.
POLE STAGE adds the DOMINANCE check (v2.2): a complex pair excludes
finite-state realizability only if it sits ON the dominant circle
(Berstel); |z_cx|/rho_max is reported whenever a complex pair
appears.

DATA.  Google's 2023 surface-code memory experiment (Zenodo 6804040):
detection_events.b8 (stim b8 packing) + DETECTOR(x, y, t) coordinates
parsed from circuit_noisy.stim.  Bulk rounds only (edge rounds carry
boundary effects).

CONTROLS.  (+) a synthetic oscillatory environment (an irrational-
rotation modulator) at matched event rate MUST fail the test - the
instrument's positive control; (-) an i.i.d. stream at matched rate
must pass.
"""
import numpy as np
import os, re, sys

rng = np.random.default_rng(2023)

# ---------------- parsing ----------------
def parse_detectors(stim_path):
    coords = []
    with open(stim_path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("DETECTOR("):
                m = re.match(r"DETECTOR\(([^)]*)\)", line)
                vals = [float(v) for v in m.group(1).split(",")]
                coords.append(tuple(vals))
    return coords      # (x, y, t) in detector-index order

def load_b8(path, num_detectors):
    nbytes = (num_detectors + 7) // 8
    raw = np.fromfile(path, dtype=np.uint8).reshape(-1, nbytes)
    bits = np.unpackbits(raw, axis=1, bitorder="little")
    return bits[:, :num_detectors]

def stabilizer_series(folder):
    coords = parse_detectors(os.path.join(folder, "circuit_noisy.stim"))
    D = len(coords)
    ev = load_b8(os.path.join(folder, "detection_events.b8"), D)
    groups = {}
    for idx, (x, y, t) in enumerate(coords):
        groups.setdefault((x, y), []).append((t, idx))
    series = {}
    for key, lst in groups.items():
        lst.sort()
        ts = [t for t, i in lst]
        idxs = [i for t, i in lst]
        series[key] = (np.array(ts), ev[:, idxs])   # shots x rounds
    return series

# ---------------- the test ----------------
def run_stats(S, m):
    """p_hat(1^n), n = 0..2m, from shots x T binary matrix S, using
    all start positions (windowed run estimator)."""
    shots, T = S.shape
    p = [1.0]
    run = np.ones_like(S)
    acc = S.copy()
    for n in range(1, 2 * m + 2):       # offset Hankel needs 2m+1
        if n > 1:
            acc = acc[:, :-1] & S[:, n - 1:]
        p.append(acc.mean())
    return np.array(p, float)

def hankel_min(p, m):
    # offset Hankel on m_k = p(1^(k+1)): H[i,j] = p[i + j + 1]
    # (v2: the n = 0 row is excluded - see header THEOREM)
    H = np.array([[p[i + j + 1] for j in range(m + 1)]
                  for i in range(m + 1)])
    return np.linalg.eigvalsh(H)[0]

def pershot_counts(S, m):
    """C[s, n-1] = number of all-ones windows of length n in shot s,
    n = 1..2m+1; W[n-1] = number of windows.  p(1^n) = C.sum(0) /
    (shots * W).  Resampling rows of C is IDENTICAL to re-forming
    runs on resampled shots (runs are within-shot objects)."""
    shots, T = S.shape
    N = 2 * m + 1
    C = np.empty((shots, N), dtype=np.float64)
    acc = S.copy()
    C[:, 0] = acc.sum(axis=1)
    for n in range(2, N + 1):
        acc = acc[:, :-1] & S[:, n - 1:]
        C[:, n - 1] = acc.sum(axis=1)
    W = np.array([T - n + 1 for n in range(1, N + 1)], float)
    return C, W

def clock_test(S, m=3, B=2000):
    """Basic-bootstrap CI for the TRUE lambda_min (B = 2000, v2.2).
    Degenerate (exactly singular) Hankels - e.g. iid streams, where
    p(1^n) = p^n is rank one - make the plug-in estimate biased
    negative; the basic bootstrap CI_true = [2 lam_hat - q_hi,
    2 lam_hat - q_lo] corrects the first-order bias (it does NOT
    restore boundary consistency - Andrews 2000; weak streams are
    read with that caveat).  Verdict SIGNED only if the corrected
    upper bound < 0.  Returns the top-moment run count for the
    run-count diagnostic."""
    shots = S.shape[0]
    C, W = pershot_counts(S, m)
    p_full = np.concatenate([[1.0], C.sum(axis=0) / (shots * W)])
    lam = hankel_min(p_full, m)
    boot = np.empty(B)
    keep = []
    for b in range(B):
        pick = rng.integers(0, shots, shots)
        w = np.bincount(pick, minlength=shots).astype(np.float64)
        pb = np.concatenate([[1.0], (w @ C) / (shots * W)])
        boot[b] = hankel_min(pb, m)
        if b < 100:
            keep.append(pb)
    boot.sort()
    q_lo, q_hi = boot[int(0.025 * B)], boot[int(0.975 * B) - 1]
    lo, hi = 2 * lam - q_hi, 2 * lam - q_lo
    verdict = "SIGNED (no reversible Moore-form HMM)" if hi < 0 \
        else "PASS (moment-compatible)"
    top_runs = int(C[:, -1].sum())
    return p_full, lam, (lo, hi), verdict, top_runs, keep

def prony_phase(p, m=3, rank_tol=2e-2):
    """Stage 2 (v2.1: ORDER-SELECTED).  Pole analysis of
    m_k = p(1^(k+1)).  Fitting a fixed order to a lower-rank
    sequence hallucinates poles (e.g. the rank-2 textbook pair
    model: exact poles {+0.2836, -0.2336}; order-3 Prony invents a
    third).  Therefore: estimate the numerical rank r of the moment
    Hankel by its singular-value profile (sigma_k / sigma_1 >
    rank_tol), then solve the order-r Prony system.  Returns
    (rank, max |Im pole|/|pole|, phase/pi of the most complex
    pole, dominance |z|/rho of that pole - v2.2)."""
    mm = np.array(p[1:2 * m + 2], float)
    H = np.array([[mm[i + j] for j in range(m + 1)]
                  for i in range(m + 1)])
    sv = np.linalg.svd(H, compute_uv=False)
    r = max(1, int((sv / max(sv[0], 1e-300) > rank_tol).sum()))
    r = min(r, m)
    A = np.array([[mm[i + j] for j in range(r)] for i in range(r)])
    b = -mm[r:2 * r]
    try:
        c = np.linalg.lstsq(A, b, rcond=None)[0]
        poles = np.roots(np.concatenate([[1.0], c[::-1]]))
    except np.linalg.LinAlgError:
        return r, 0.0, 0.0, 0.0
    mag = np.abs(poles)
    if len(poles) == 0 or mag.max() < 1e-12:
        return r, 0.0, 0.0, 0.0
    imfrac = np.abs(poles.imag) / np.maximum(mag, 1e-300)
    k = int(np.argmax(imfrac))
    # v2.2 DOMINANCE: a complex pair obstructs only on the dominant
    # circle (Berstel); report its modulus relative to the spectral
    # radius of the fitted pole set.
    dom = float(mag[k] / mag.max())
    return r, float(imfrac[k]), float(abs(np.angle(poles[k])) / np.pi), dom

def _fit_poles(mm, r):
    A = np.array([[mm[i + j] for j in range(r)] for i in range(r)])
    b = -mm[r:2 * r]
    try:
        c = np.linalg.lstsq(A, b, rcond=None)[0]
        return np.roots(np.concatenate([[1.0], c[::-1]]))
    except np.linalg.LinAlgError:
        return np.array([])

def pole_scan(p, boot_ps, m=3, im_tol=0.05):
    """v2.2 RANK SCAN (operationalizes 'robust to rank choice and
    resampling' + the DOMINANCE condition).  Conservative primary
    rank selection protects against hallucinated poles but can
    UNDER-select and miss a genuine subnoise pair (the oscillatory
    control: sigma2/sigma1 ~ 6e-3 < 2e-2).  So: at every order
    r = 1..m fit poles on the full sample; whenever a complex pair
    appears, refit at the same order on each bootstrap moment vector
    and report (stability = fraction of resamples with a pair,
    median |Im|/|z|, median dominance |z_cx|/rho, median phase/pi).
    A clock candidate = some order with stability ~1, dominance ~1,
    stable irrational phase.  Order-misselection artifacts are
    resample-UNSTABLE or subdominant - the discriminator."""
    mm = np.array(p[1:2 * m + 2], float)
    scan = []
    for r in range(1, m + 1):
        poles = _fit_poles(mm, r)
        if len(poles) == 0:
            continue
        mag = np.abs(poles)
        if mag.max() < 1e-12:
            continue
        imf = np.abs(poles.imag) / np.maximum(mag, 1e-300)
        k = int(np.argmax(imf))
        if imf[k] < im_tol:
            continue
        stats = []
        for pb in boot_ps:
            mb = np.array(pb[1:2 * m + 2], float)
            pl = _fit_poles(mb, r)
            if len(pl) == 0:
                stats.append((0.0, 0.0, 0.0)); continue
            mg = np.abs(pl)
            if mg.max() < 1e-12:
                stats.append((0.0, 0.0, 0.0)); continue
            imb = np.abs(pl.imag) / np.maximum(mg, 1e-300)
            kb = int(np.argmax(imb))
            stats.append((float(imb[kb] >= im_tol),
                          float(mg[kb] / mg.max()),
                          float(abs(np.angle(pl[kb])) / np.pi)))
        stats = np.array(stats)
        stability = float(stats[:, 0].mean()) if len(stats) else 0.0
        dom_med = float(np.median(stats[stats[:, 0] > 0, 1])) \
            if stability > 0 else 0.0
        ph_med = float(np.median(stats[stats[:, 0] > 0, 2])) \
            if stability > 0 else 0.0
        scan.append((r, float(imf[k]),
                     float(mag[k] / mag.max()), stability,
                     dom_med, ph_med))
    return scan

def scan_text(scan):
    hits = [s for s in scan if s[3] >= 0.5]
    if not hits:
        return "cx-scan: none stable"
    return "cx-scan: " + "; ".join(
        f"r{r}: stab {st:.2f} dom {dm:.2f} phase {ph:.2f}pi"
        for (r, imf, dom, st, dm, ph) in hits)

# ---------------- main ----------------
def analyze_folder(folder, m=3, bulk=(2, None)):
    name = os.path.basename(folder)
    series = stabilizer_series(folder)
    print(f"\n--- {name}: {len(series)} stabilizers ---")
    results = []
    for key in sorted(series):
        ts, S = series[key]
        # bulk rounds only
        tmax = ts.max()
        mask = (ts >= bulk[0]) & (ts <= tmax - 2)
        S = S[:, mask]
        if S.shape[1] < 2 * m + 2:
            continue
        rate = S.mean()
        drift = np.abs(S.mean(axis=0) - rate).max()
        p, lam, (lo, hi), verdict, nrun, keep = clock_test(S, m=m)
        rk, imf, ph, dom = prony_phase(p, m=m)
        scan = pole_scan(p, keep, m=m)
        results.append((key, rate, lam, lo, hi, verdict, rk, imf, ph,
                        dom, nrun, scan))
        domtxt = f" dom {dom:.3f}" if imf > 1e-9 else ""
        print(f"  stab {key}: rate {rate:.4f}  round-drift {drift:.4f}"
              f"  lam_min {lam:+.2e}  CI [{lo:+.2e}, {hi:+.2e}]"
              f"  poles: rank {rk} |Im|/|p| {imf:.3f}{domtxt}"
              f"  top-runs {nrun}  {scan_text(scan)}"
              f"  -> {verdict}")
    return results

if __name__ == "__main__":
    base = "/tmp/qec_data"
    folders = [f for f in sorted(os.listdir(base))
               if "r25" in f and os.path.isdir(os.path.join(base, f))]
    print("== THE CLOCK TEST ON REAL SURFACE-CODE SYNDROME DATA ==")
    print("   (Google 2023 memory experiment, Zenodo 6804040;")
    print("    50,000 shots per folder; bulk rounds; m = 3 Hankel)")
    all_res = []
    for f in folders[:6]:
        all_res += analyze_folder(os.path.join(base, f))

    n_pass = sum(1 for r in all_res if "PASS" in r[5])
    n_sign = len(all_res) - n_pass
    print(f"\n== AGGREGATE: {n_pass} PASS, {n_sign} SIGNED of"
          f" {len(all_res)} stabilizer streams ==")
    # conservative Bonferroni (64 tests, family 5%): inflate the
    # upper CI margin by z_{1-0.05/(2*64)} / z_{0.975} ~ 1.6
    # (normal approximation) and ask whether every stream stays < 0
    bonf_ok = all((r[2] + 1.6 * (r[4] - r[2])) < 0 for r in all_res)
    worst = max((r[2] + 1.6 * (r[4] - r[2])) for r in all_res)
    runs = sorted(r[10] for r in all_res)
    n_scan = sum(1 for r in all_res
                 if any(s[3] >= 0.5 for s in r[11]))
    n_clock = sum(1 for r in all_res
                  if any(s[3] >= 0.5 and s[4] >= 0.95 for s in r[11]))
    print(f"   rank-scan: {n_scan}/{len(all_res)} streams show a"
          f" resample-stable complex pair at any order <= 3;"
          f" {n_clock}/{len(all_res)} show a stable pair that is"
          f" also DOMINANT (median |z|/rho >= 0.95) - the clock"
          f" signature (the oscillatory control shows dom 1.00)")
    print(f"   Bonferroni(64 tests, 5% family, x1.6 margins): "
          f"{'ALL SIGNED SURVIVE' if bonf_ok else 'NOT ALL SURVIVE'}"
          f" (worst inflated upper bound {worst:+.2e})")
    print(f"   top-moment run counts p(1^7): min {runs[0]}, median"
          f" {runs[len(runs)//2]}, max {runs[-1]}")

    # ---------------- controls ----------------
    print("\n== controls ==")
    # (-) i.i.d. at matched rate
    rate = np.mean([r[1] for r in all_res]) if all_res else 0.12
    S_iid = (rng.uniform(size=(50000, 22)) < rate).astype(np.uint8)
    p, lam, (lo, hi), verdict, _, keep = clock_test(S_iid, m=3)
    print(f"  iid control (rate {rate:.3f}):       lam_min {lam:+.2e}"
          f"  CI [{lo:+.2e}, {hi:+.2e}]  {scan_text(pole_scan(p, keep))}"
          f"  -> {verdict}")
    # (+) oscillatory (irrational-rotation) environment, matched rate
    th = 1.0
    phase0 = rng.uniform(0, 2 * np.pi, size=(50000, 1))
    tgrid = np.arange(22)[None, :]
    prob = rate * (1 + 0.9 * np.cos(phase0 + th * tgrid))
    S_osc = (rng.uniform(size=(50000, 22)) < prob).astype(np.uint8)
    p, lam, (lo, hi), verdict, _, keep = clock_test(S_osc, m=3)
    rk, imf, ph, dom = prony_phase(p, m=3)
    print(f"  oscillatory control (same rate):    lam_min {lam:+.2e}"
          f"  CI [{lo:+.2e}, {hi:+.2e}]  poles: rank {rk}"
          f" |Im|/|p| {imf:.3f}  {scan_text(pole_scan(p, keep))}"
          f"  -> {verdict}")
    print("\n  (the instrument: a hidden irrational rotation SIGNS the")
    print("   Hankel at matched rate and statistics, while iid passes -")
    print("   whatever the device data shows is therefore a statement")
    print("   about the device, not about the test's power)")
