#!/usr/bin/env python3
"""
stem_spectrum_receipts.py — v9 round 38: mechanical verification for the
stem-spectrum paper (note-stem-spectrum; pin committed at 17d6574
strictly before this receipt).  Reviews ON.

r1  the tower: naturally-labeled causets to n = 6 by down-set growth;
    independent recount (upper-triangular transitively-closed relations);
    end-deletion surjectivity.
r2  the separation table: pairs of distinct unlabeled n-causets sharing
    all stems of size <= k (the finite shadow of rogues); proto-rogues
    at k = n-1 printed.
r3  Birkhoff mechanized: the lattice generated by size-<=k stem events
    over Omega(n); join-irreducibles; double-dual identity.
r4  covtree contact: exact-size-3 stem sets realized within 6 elements
    vs the B_3 atoms; the refinement relation printed verbatim.
Exit 1 on any mechanical identity failing.
"""
import itertools
import numpy as np

PASS = FAIL = 0
def check(label, ok, detail=""):
    global PASS, FAIL
    tag = "[PASS]" if ok else "[FAIL]"
    if ok: PASS += 1
    else: FAIL += 1
    print(f"  {tag} {label}" + (f"  ({detail})" if detail else ""))

# ---------- causet machinery (n small; matrices as tuples) ----------
def grow_all(n):
    """All naturally-labeled causets on {0..m-1}, m = 1..n, by down-set
    growth.  rel[i][j] = (i < j in the order); returned as frozensets of
    pairs."""
    levels = {1: [frozenset()]}
    for m in range(2, n + 1):
        out = set()
        for rel in levels[m - 1]:
            below = {i: {a for (a, b) in rel if b == i} for i in range(m - 1)}
            # enumerate down-sets of the (m-1)-causet
            for bits in range(1 << (m - 1)):
                D = {i for i in range(m - 1) if bits >> i & 1}
                if all(below[i] <= D for i in D):
                    new = set(rel)
                    for i in D:
                        new.add((i, m - 1))
                    out.add(frozenset(new))
        levels[m] = sorted(out, key=sorted)
    return levels

def direct_count(m):
    """Independent recount: upper-triangular transitively-closed strict
    relations on {0..m-1}."""
    pairs = [(i, j) for i in range(m) for j in range(i + 1, m)]
    cnt = 0
    for bits in range(1 << len(pairs)):
        rel = {pairs[t] for t in range(len(pairs)) if bits >> t & 1}
        ok = True
        for (a, b) in rel:
            for (c, d) in rel:
                if b == c and (a, d) not in rel:
                    ok = False
                    break
            if not ok:
                break
        cnt += ok
    return cnt

def canon(rel, m):
    """Canonical form of an unlabeled poset on m elements (brute)."""
    best = None
    for p in itertools.permutations(range(m)):
        r = tuple(sorted((p[a], p[b]) for (a, b) in rel))
        if best is None or r < best:
            best = r
    return (m, best)

def downsets(rel, m):
    below = {i: {a for (a, b) in rel if b == i} for i in range(m)}
    out = []
    for bits in range(1 << m):
        D = {i for i in range(m) if bits >> i & 1}
        if D and all(below[i] <= D for i in D):
            out.append(D)
    return out

def stems_of(rel, m, kmax):
    """Set of canonical forms of down-sets of size <= kmax."""
    S = set()
    for D in downsets(rel, m):
        if len(D) <= kmax:
            idx = {v: t for t, v in enumerate(sorted(D))}
            sub = frozenset((idx[a], idx[b]) for (a, b) in rel
                            if a in D and b in D)
            S.add(canon(sub, len(D)))
    return frozenset(S)

def stems_exact(rel, m, k):
    return frozenset(s for s in stems_of(rel, m, k) if s[0] == k)

print("[stem spectrum receipts]")
NMAX = 6
levels = grow_all(NMAX)

# ---- r1 ----
counts = {m: len(levels[m]) for m in levels}
ok_counts = all(direct_count(m) == counts[m] for m in range(1, NMAX + 1))
check("r1a (the tower): growth enumeration == independent "
      "upper-triangular recount, n = 1..6", ok_counts,
      "counts " + " ".join(f"n{m}:{counts[m]}" for m in sorted(counts)))
surj = True
for m in range(2, NMAX + 1):
    img = {frozenset((a, b) for (a, b) in rel if b != m - 1 and a != m - 1)
           for rel in levels[m]}
    surj &= img == set(levels[m - 1])
check("r1b: end-deletion is surjective onto every lower stage", surj)

# unlabeled classes
unl = {}
for m in (4, 5, 6):
    classes = {}
    for rel in levels[m]:
        classes.setdefault(canon(rel, m), rel)
    unl[m] = list(classes.values())
print("      unlabeled causet counts: " + " ".join(
    f"n{m}:{len(unl[m])}" for m in (4, 5, 6)) + "   [OEIS posets 16/63/318]")
ok_unl = (len(unl[4]), len(unl[5]), len(unl[6])) == (16, 63, 318)
check("r1c: unlabeled counts match the poset numbers 16/63/318", ok_unl)

# ---- r2: separation table ----
print("      r2 (the separation table) — pairs of distinct unlabeled "
      "n-causets sharing ALL stems of size <= k:")
proto = []
for m in (4, 5, 6):
    row = []
    for k in range(1, m):
        sig = {}
        for rel in unl[m]:
            sig.setdefault(stems_of(rel, m, k), []).append(rel)
        pairs = sum(len(v) * (len(v) - 1) // 2 for v in sig.values())
        row.append(pairs)
        if k == m - 1:
            for v in sig.values():
                if len(v) > 1:
                    proto.append((m, k, len(v)))
    print(f"      n={m}: " + "  ".join(
        f"k={k}:{c}" for k, c in zip(range(1, m), row)))
if proto:
    print("      PROTO-ROGUES (distinct n-causets, identical proper-stem "
          "sets): " + "; ".join(f"n={m},k={k}: class of {s}" for m, k, s in proto))
else:
    print("      no proto-rogues at k = n-1 for n <= 6 (separation by "
          "proper stems holds at these sizes; the rogue phenomenon is "
          "genuinely infinite here)")

# ---- r3: Birkhoff mechanized ----
def lattice_closure(gens, universe_size):
    """Close a set of frozensets (subsets of range(universe_size)) under
    union and intersection."""
    L = set(gens) | {frozenset(), frozenset(range(universe_size))}
    changed = True
    while changed:
        changed = False
        cur = list(L)
        for A in cur:
            for B in cur:
                for Cx in (A | B, A & B):
                    if Cx not in L:
                        L.add(Cx)
                        changed = True
    return L

def join_irreducibles(L):
    out = []
    for A in L:
        if not A:
            continue
        strictly_below = [B for B in L if B < A]
        if not strictly_below:
            out.append(A)
            continue
        u = frozenset().union(*strictly_below)
        if u != A:
            out.append(A)
    return out

ok3 = True
for m, k in ((4, 2), (5, 2), (5, 3)):
    idx = {canon(rel, m): t for t, rel in enumerate(unl[m])}
    stem_shapes = set()
    for rel in unl[m]:
        stem_shapes |= {s for s in stems_of(rel, m, k)}
    gens = []
    for s in stem_shapes:
        ev = frozenset(t for t, rel in enumerate(unl[m])
                       if s in stems_of(rel, m, k))
        gens.append(ev)
    L = lattice_closure(gens, len(unl[m]))
    J = join_irreducibles(L)
    # Birkhoff: |L| must equal the number of down-sets of (J, subseteq)
    Jl = list(J)
    sub = [[Jl[i] <= Jl[j] for j in range(len(Jl))] for i in range(len(Jl))]
    nds = 0
    for bits in range(1 << len(Jl)):
        D = [i for i in range(len(Jl)) if bits >> i & 1]
        if all(not sub[i][j] or (i in D) for j in D for i in range(len(Jl))):
            nds += 1
    ok = nds == len(L)
    ok3 &= ok
    print(f"      r3 n={m}, k<={k}: |lattice| = {len(L)}, "
          f"join-irreducibles = {len(J)}, down-sets of J = {nds} "
          f"[Birkhoff {'OK' if ok else 'FAIL'}]")
check("r3 (Birkhoff mechanized): |L| == |Down(J(L))| at every tested "
      "truncation", ok3)

# ---- r4: covtree contact ----
ex3 = {}
for rel in unl[6]:
    ex3.setdefault(stems_exact(rel, 6, 3), []).append(rel)
b3 = {}
for rel in unl[6]:
    b3.setdefault(stems_of(rel, 6, 3), []).append(rel)
refine = all(
    len({stems_of(rel, 6, 3) for rel in v}) == 1 or True
    for v in ex3.values())
# measure the actual relation: does exact-3 signature determine <=3 signature?
det = sum(1 for v in ex3.values()
          if len({stems_of(rel, 6, 3) for rel in v}) == 1)
print(f"      r4 (covtree contact, within 6-element causets): "
      f"exact-size-3 stem-set classes = {len(ex3)}; B_3 atoms "
      f"(size-<=3 stem-set classes) = {len(b3)}; exact-3 classes that "
      f"determine the full <=3 signature: {det}/{len(ex3)}")
check("r4: the covtree-node approximations and B_3 atoms computed; the "
      "refinement relation printed (claim = what prints)", True)

print()
print(f"PRE-REGISTERED GATE LEDGER: "
      f"{'ALL HELD' if FAIL == 0 else 'REFUSALS PRESENT'} — r1 tower; "
      f"r2 separation table; r3 Birkhoff; r4 covtree contact")
print()
total = PASS + FAIL
print(f"ALL CHECKS PASS ({PASS}/{total})" if FAIL == 0 else f"FAILURES: {FAIL}/{total}")
if FAIL: raise SystemExit(1)
