#!/usr/bin/env python3
"""
v6_p31b: epsilon screening and seam selection (Paper 31, part B).

p31a reduced the Z6 lattice to ONE identification: (Y-det) -
hypercharge is the relative determinant character Y6 = 3b - 2a of
the U(3) x U(2) record tower.  This script supplies the internal
mechanism and the uniqueness receipts, INCLUDING the honest negative
result a hostile reviewer needs.

 (i)   SEALED-EPSILON SCREENING (the mechanism, lattice receipt):
       the epsilon records of the two fibers - the full
       antisymmetrizations, det3 = (3,0) and det2 = (0,2) in
       (a, b)-charge - are SEALS (P18 R4: the baryon carries only
       det charge; baryon channels seal).  Hypothesis (E): charges
       generated by sealed epsilon records are screened (a condensed
       seal trivializes its sector class).  Lattice consequence,
       computed: the recordable charge data is
           Z^2 / <(3,0),(0,2)>  x  (continuous rank-1 ray
           orthogonal to the epsilon directions)
       = (tau, sigma) discrete data x the hypercharge ray
       Y6 = 3b - 2a: EXACTLY the (Y-det) structure, hence the Z6
       identity.
 (ii)  SEAM + ANOMALY UNIQUENESS: given only the floor SHELLS
       (SU(3) x SU(2) content), the neutral Yukawa seam system plus
       the linear anomaly is a homogeneous linear system whose
       kernel is ONE-dimensional - and the lattice-minimal integer
       generator is the SM hypercharge assignment exactly.
 (iii) THE HONEST NEGATIVE: the seam system alone does NOT select
       the residue class: the SM ray also fits the wrong-class
       formula Y6 = a (pure color-det character) at the level of
       residues - so residue selection genuinely NEEDS (E) (or an
       equivalent internal principle), and the paper says so.
"""
import numpy as np
from itertools import product

# ---------- (i) the screening lattice ----------
print("== (i) sealed-epsilon screening: the lattice computation ==")
eps3, eps2 = np.array([3, 0]), np.array([0, 2])
# discrete part: Z^2 / <(3,0),(0,2)>
reps = sorted({(a % 3, b % 2) for a in range(-9, 10)
               for b in range(-9, 10)})
print(f"  Z^2 / <(3,0),(0,2)> = {len(reps)} classes"
      f" = Z_3 x Z_2 (tau, sigma): {reps}")
# continuous part: recordable charge FUNCTIONALS are the covectors
# (p, q) [Y6 = p a + q b] vanishing on the combined seal direction
# (3,2) = eps3 + eps2 (one unit of each epsilon):
covs = [(p, q) for p in range(-9, 10) for q in range(-9, 10)
        if 3 * p + 2 * q == 0 and (p, q) != (0, 0)]
gen = min(covs, key=lambda t: abs(t[0]) + abs(t[1]))
if gen[0] > 0:
    gen = (-gen[0], -gen[1])
print(f"  charge functionals Y6 = p a + q b vanishing on the seal")
print(f"  direction (3,2): the covector lattice Z x {gen}")
ok_gen = gen == (-2, 3)
print(f"  minimal generator = (-2, 3), i.e. Y6 = 3b - 2a:"
      f" {'PASS' if ok_gen else 'FAIL'}")
Y = lambda a, b: 3 * b - 2 * a
viol = sum((2 * (a % 3) + 3 * (b % 2) + Y(a, b)) % 6
           for a in range(-6, 7) for b in range(-6, 7))
print(f"  Z6 congruence violations with this Y: {viol}")
print("  -> hypothesis (E) [sealed epsilons screen their charges]")
print("     forces: discrete data (tau, sigma), continuous data the")
print("     single ray Y6 = 3b - 2a - the (Y-det) structure DERIVED,")
print("     and with it the Z6 lattice as an identity.")

# ---------- (ii) seam + anomaly uniqueness ----------
print("\n== (ii) the seam system: kernel dim 1, generator = SM ==")
# unknowns: y = (Q, u^c, d^c, L, e^c, nu^c, H)
A = np.array([
    [1, 1, 0, 0, 0, 0, -1],     # Q u^c Htilde
    [1, 0, 1, 0, 0, 0,  1],     # Q d^c H
    [0, 0, 0, 1, 1, 0,  1],     # L e^c H
    [0, 0, 0, 1, 0, 1, -1],     # L nu^c Htilde
    [0, 0, 0, 0, 0, 2,  0],     # Majorana nu^c nu^c
    [6, 3, 3, 2, 1, 1,  0],     # linear (grav-U(1)) anomaly
    [2, 1, 1, 0, 0, 0,  0],     # SU(3)^2-U(1) anomaly (linear in Y)
    [3, 0, 0, 1, 0, 0,  0],     # SU(2)^2-U(1) anomaly (linear in Y)
], dtype=float)
ns = []
u, s, vt = np.linalg.svd(A)
null_dim = 7 - np.linalg.matrix_rank(A, tol=1e-10)
print(f"  seam + anomaly system: rank = {np.linalg.matrix_rank(A)},"
      f" kernel dimension = {null_dim}")
v = vt[-1]
v = v / np.abs(v[np.abs(v) > 1e-9]).min()
v = np.round(v).astype(int)
if v[0] < 0:
    v = -v
res = np.abs(A @ v).max()
labels = ["Q", "u^c", "d^c", "L", "e^c", "nu^c", "H"]
sm = [1, -4, 2, -3, 6, 0, -3]
print("   field:      " + "  ".join(f"{l:>4s}" for l in labels))
print("   kernel gen: " + "  ".join(f"{x:4d}" for x in v))
print("   SM (Y6):    " + "  ".join(f"{x:4d}" for x in sm))
print(f"  residual |A v| = {res:.1e};  generator = SM:"
      f" {'PASS' if list(v) == sm else 'FAIL'}")
print("  -> given the shells, the four seams + Majorana seal, and")
print("     the three Y-linear anomaly conditions (grav, SU(3)^2-Y,")
print("     SU(2)^2-Y), the hypercharge assignment is UNIQUE up to")
print("     scale and the minimal integer point is the Standard")
print("     Model - the P20 invariant-tensor receipts re-derived at")
print("     lattice level.  (Without the two gauge-squared rows the")
print("     kernel is 2-dimensional: they are load-bearing and so")
print("     imported, named, as in P14.)")

# ---------- (iii) the honest negative ----------
print("\n== (iii) what the seams do NOT do (honest negative) ==")
tau = {"Q": 1, "u^c": 2, "d^c": 2, "L": 0, "e^c": 0, "nu^c": 0,
       "H": 0}
ok_wrong = all((sm_i - tau[l]) % 3 == 0
               for sm_i, l in zip(sm, labels))
print(f"  the SM ray ALSO satisfies the residue pattern of the")
print(f"  WRONG-class formula Y6 = a (pure color-det):"
      f" Y ≡ tau mod 3 on all fields: {ok_wrong}")
print("  -> the seam + anomaly system does NOT select the residue")
print("     class (alpha, beta): it fixes the RAY, not the class.")
print("     Residue selection - the actual content of the Z6")
print("     quotient - comes from hypothesis (E) alone in this")
print("     campaign.  (E) is therefore the single load-bearing new")
print("     identification, stated as such; its promotion to a")
print("     theorem (condensed seals trivialize sector classes, in")
print("     the record DR category) is the named residue of")
print("     (Z6-int).")
print("== p31b done ==")
