#!/usr/bin/env python3
"""
v6_p17b: the 4d filter and the Standard Model receipts (Paper 17).

The 4d analogue of the P14 predicates for a U(1) factor: in the
all-left-handed Weyl convention with integer charges,

   MIXED-GRAV:  sum q   = 0
   GAUGE CUBE:  sum q^3 = 0        [named import: the 4d triangle]

 (i)  MINIMAL 4d CHIRAL SOLUTIONS: exhaustive enumeration of genuinely
      chiral nonzero-integer multisets (not invariant under q -> -q)
      passing both sums - minimal size and the small census.
 (ii) THE SM HYPERCHARGE RECEIPT: one generation of the Standard Model
      in 6Y units (all-left Weyl): Q: 6 x (+1); u^c: 3 x (-4);
      d^c: 3 x (+2); L: 2 x (-3); e^c: 1 x (+6).  Both sums vanish
      EXACTLY - the hypercharge miracle passes the record filter, per
      generation (nu^c, q = 0, is filter-neutral).
 (iii) THE Z_6 QUOTIENT RECEIPT: every SM Weyl field satisfies
      2t + 3d + Y6 = 0 mod 6 (t = triality, d = duality, Y6 = 6Y):
      the SM's true gauge code is the Z_6 QUOTIENT of
      SU(3) x SU(2) x U(1) - in record terms, the relation-code
      character lattice is the quotient lattice.  Machine-checked
      field by field.
 (iv) STRUCTURE SCAN: among the minimal 4d chiral solutions, which
      carry an SM-like signature (a charge of multiplicity 3 - a
      color-triplet shadow)?  Census reported.
"""
import numpy as np
from itertools import combinations_with_replacement

# ---------- (i) minimal 4d chiral solutions ----------
print("== (i) minimal genuinely chiral 4d U(1) spectra ==")
def chiral_solutions(size, qmax):
    sols = []
    pool = [q for q in range(-qmax, qmax + 1) if q != 0]
    for combo in combinations_with_replacement(pool, size):
        if sum(combo) == 0 and sum(q ** 3 for q in combo) == 0:
            neg = sorted(-q for q in combo)
            if neg != sorted(combo):              # genuinely chiral
                sols.append(tuple(sorted(combo)))
    return sorted(set(sols))

for size in (3, 4, 5):
    s = chiral_solutions(size, 9)
    print(f"  size {size}, |q| <= 9: {len(s)} genuinely chiral solutions"
          + (f"   first: {list(s[0])}" if s else ""))
s6 = chiral_solutions(6, 9)
print(f"  size 6, |q| <= 9: {len(s6)};  smallest by max charge: "
      f"{list(sorted(s6, key=lambda t: max(abs(q) for q in t))[0])}")
print("  -> the 4d filter is far more selective than the 2d one: the")
print("     cubic constraint kills everything below size 5.")

# ---------- (ii) the SM hypercharge receipt ----------
print("\n== (ii) the Standard Model passes the record filter ==")
gen = [1] * 6 + [-4] * 3 + [2] * 3 + [-3] * 2 + [6]
print(f"  one generation, all-left Weyl, 6Y units:")
print(f"   Q: 6x(+1), u^c: 3x(-4), d^c: 3x(+2), L: 2x(-3), e^c: 1x(+6)")
print(f"   sum q   = {sum(gen)}        sum q^3 = {sum(q**3 for q in gen)}")
print(f"   ({len(gen)} Weyl fields; nu^c at q = 0 is filter-neutral)")
print("  -> BOTH sums vanish exactly: the hypercharge miracle is a")
print("     record-filter receipt, generation by generation; with three")
print("     generations the sums scale by 3 and still vanish (the")
print("     factorization theorem of p17a in the 4d setting).")

# ---------- (iii) the Z_6 quotient receipt ----------
print("\n== (iii) the SM code is the Z_6 quotient ==")
fields = [("Q",   1, 1,  1, 6), ("u^c", -1, 0, -4, 3),
          ("d^c", -1, 0,  2, 3), ("L",   0, 1, -3, 2),
          ("e^c",  0, 0,  6, 1)]
ok = True
for name, t, dd, y6, mult in fields:
    val = (2 * t + 3 * dd + y6) % 6
    ok = ok and (val == 0)
    print(f"   {name:4s}: 2t + 3d + Y6 = {2*t + 3*dd + y6:+3d} = {val} mod 6")
print(f"  all fields pass: {ok}")
print("  -> every SM Weyl field is invariant under the Z_6 subgroup")
print("     generated by (color triality, weak duality, hypercharge")
print("     phase): the faithful gauge code is SU(3)xSU(2)xU(1) / Z_6,")
print("     and in record terms the relation-code CHARACTER LATTICE is")
print("     the quotient lattice - the object the (M) search must")
print("     target, not the naive product.")

# ---------- (iv) structure scan ----------
print("\n== (iv) color-triplet shadows in the minimal solutions ==")
trip = [s for s in s6 if any(s.count(q) >= 3 for q in set(s))]
print(f"  size-6 solutions with a charge of multiplicity >= 3: "
      f"{len(trip)}/{len(s6)}")
for s in trip[:5]:
    print(f"    {list(s)}")
print("  -> a fraction of the minimal chiral spectra already carry the")
print("     multiplicity-3 (color-shadow) structure; combined with")
print("     p17a's closure census (Z_3 universal at minimal scope) the")
print("     Phase-II target is named: NONABELIAN lift of the")
print("     multiplicity-3 charges to triality-code representations -")
print("     blocked on D10 (nonabelian record statistics), as expected.")
print("== p17b done ==")
